; Total rules: 397
; Rulemap entries: 127
; ============================================================
; TTS Rule Tables - auto-generated by gen_tts_rules.py
; Do not edit manually.
; ============================================================

; ------------------------------------------------------------
; String constants
; ------------------------------------------------------------
tts_str_0:
    DEFM "A", 0
tts_str_1:
    DEFM " ", 0
tts_str_2:
    DEFM "ARE", 0
tts_str_3:
    DEFM "AR", 0
tts_str_4:
    DEFM "O", 0
tts_str_5:
    DEFM "#", 0
tts_str_6:
    DEFM "^", 0
tts_str_7:
    DEFM "AS", 0
tts_str_8:
    DEFM "WA", 0
tts_str_9:
    DEFM "AW", 0
tts_str_10:
    DEFM " :", 0
tts_str_11:
    DEFM "ANY", 0
tts_str_12:
    DEFM "^+#", 0
tts_str_13:
    DEFM "#:", 0
tts_str_14:
    DEFM "ALLY", 0
tts_str_15:
    DEFM "AL", 0
tts_str_16:
    DEFM "AGAIN", 0
tts_str_17:
    DEFM "AG", 0
tts_str_18:
    DEFM "E", 0
tts_str_19:
    DEFM "^+:#", 0
tts_str_20:
    DEFM "^+ ", 0
tts_str_21:
    DEFM "^%", 0
tts_str_22:
    DEFM "ARR", 0
tts_str_23:
    DEFM "AIR", 0
tts_str_24:
    DEFM "AI", 0
tts_str_25:
    DEFM "AY", 0
tts_str_26:
    DEFM "AU", 0
tts_str_27:
    DEFM "ALS", 0
tts_str_28:
    DEFM "ALK", 0
tts_str_29:
    DEFM "ABLE", 0
tts_str_30:
    DEFM "ANG", 0
tts_str_31:
    DEFM "+", 0
tts_str_32:
    DEFM "BE", 0
tts_str_33:
    DEFM "^#", 0
tts_str_34:
    DEFM "BEING", 0
tts_str_35:
    DEFM "BOTH", 0
tts_str_36:
    DEFM "BUS", 0
tts_str_37:
    DEFM "BUIL", 0
tts_str_38:
    DEFM "B", 0
tts_str_39:
    DEFM "CH", 0
tts_str_40:
    DEFM "^E", 0
tts_str_41:
    DEFM " S", 0
tts_str_42:
    DEFM "CI", 0
tts_str_43:
    DEFM "EN", 0
tts_str_44:
    DEFM "C", 0
tts_str_45:
    DEFM "CK", 0
tts_str_46:
    DEFM "COM", 0
tts_str_47:
    DEFM "%", 0
tts_str_48:
    DEFM "DED", 0
tts_str_49:
    DEFM ".E", 0
tts_str_50:
    DEFM "D", 0
tts_str_51:
    DEFM "#:^E", 0
tts_str_52:
    DEFM "DE", 0
tts_str_53:
    DEFM "DO", 0
tts_str_54:
    DEFM "DOES", 0
tts_str_55:
    DEFM "DOING", 0
tts_str_56:
    DEFM "DOW", 0
tts_str_57:
    DEFM "DU", 0
tts_str_58:
    DEFM "':^", 0
tts_str_59:
    DEFM "ED", 0
tts_str_60:
    DEFM "D ", 0
tts_str_61:
    DEFM "EV", 0
tts_str_62:
    DEFM "ER", 0
tts_str_63:
    DEFM "ERI", 0
tts_str_64:
    DEFM "EVEN", 0
tts_str_65:
    DEFM "W", 0
tts_str_66:
    DEFM "T", 0
tts_str_67:
    DEFM "EW", 0
tts_str_68:
    DEFM "S", 0
tts_str_69:
    DEFM "R", 0
tts_str_70:
    DEFM "L", 0
tts_str_71:
    DEFM "Z", 0
tts_str_72:
    DEFM "N", 0
tts_str_73:
    DEFM "J", 0
tts_str_74:
    DEFM "TH", 0
tts_str_75:
    DEFM "SH", 0
tts_str_76:
    DEFM "#:S", 0
tts_str_77:
    DEFM "ES", 0
tts_str_78:
    DEFM "#:C", 0
tts_str_79:
    DEFM "#:G", 0
tts_str_80:
    DEFM "#:Z", 0
tts_str_81:
    DEFM "#:X", 0
tts_str_82:
    DEFM "#:J", 0
tts_str_83:
    DEFM "#:CH", 0
tts_str_84:
    DEFM "#:SH", 0
tts_str_85:
    DEFM "S ", 0
tts_str_86:
    DEFM "ELY", 0
tts_str_87:
    DEFM "EMENT", 0
tts_str_88:
    DEFM "EFUL", 0
tts_str_89:
    DEFM "EE", 0
tts_str_90:
    DEFM "EARN", 0
tts_str_91:
    DEFM "EAR", 0
tts_str_92:
    DEFM "EAD", 0
tts_str_93:
    DEFM "EA", 0
tts_str_94:
    DEFM "SU", 0
tts_str_95:
    DEFM "EIGH", 0
tts_str_96:
    DEFM "EI", 0
tts_str_97:
    DEFM "EYE", 0
tts_str_98:
    DEFM "EY", 0
tts_str_99:
    DEFM "EU", 0
tts_str_100:
    DEFM "FUL", 0
tts_str_101:
    DEFM "F", 0
tts_str_102:
    DEFM "GIV", 0
tts_str_103:
    DEFM "G", 0
tts_str_104:
    DEFM "I^", 0
tts_str_105:
    DEFM "GE", 0
tts_str_106:
    DEFM "GGES", 0
tts_str_107:
    DEFM "GG", 0
tts_str_108:
    DEFM " B#", 0
tts_str_109:
    DEFM "GREAT", 0
tts_str_110:
    DEFM "GH", 0
tts_str_111:
    DEFM "HAV", 0
tts_str_112:
    DEFM "HERE", 0
tts_str_113:
    DEFM "HOUR", 0
tts_str_114:
    DEFM "HOW", 0
tts_str_115:
    DEFM "H", 0
tts_str_116:
    DEFM "IN", 0
tts_str_117:
    DEFM "I", 0
tts_str_118:
    DEFM "IER", 0
tts_str_119:
    DEFM "#:R", 0
tts_str_120:
    DEFM "IED", 0
tts_str_121:
    DEFM "IEN", 0
tts_str_122:
    DEFM "IE", 0
tts_str_123:
    DEFM "IR", 0
tts_str_124:
    DEFM "IZ", 0
tts_str_125:
    DEFM "IS", 0
tts_str_126:
    DEFM "D%", 0
tts_str_127:
    DEFM "+^", 0
tts_str_128:
    DEFM "^+", 0
tts_str_129:
    DEFM "T%", 0
tts_str_130:
    DEFM "#:^", 0
tts_str_131:
    DEFM "IGH", 0
tts_str_132:
    DEFM "ILD", 0
tts_str_133:
    DEFM "IGN", 0
tts_str_134:
    DEFM "IQUE", 0
tts_str_135:
    DEFM "K", 0
tts_str_136:
    DEFM "LO", 0
tts_str_137:
    DEFM "C#", 0
tts_str_138:
    DEFM "LEAD", 0
tts_str_139:
    DEFM "MOV", 0
tts_str_140:
    DEFM "M", 0
tts_str_141:
    DEFM "NG", 0
tts_str_142:
    DEFM "NGL", 0
tts_str_143:
    DEFM "NK", 0
tts_str_144:
    DEFM "NOW", 0
tts_str_145:
    DEFM "OF", 0
tts_str_146:
    DEFM "OROUGH", 0
tts_str_147:
    DEFM "OR", 0
tts_str_148:
    DEFM "ORS", 0
tts_str_149:
    DEFM "ONE", 0
tts_str_150:
    DEFM "OW", 0
tts_str_151:
    DEFM "OVER", 0
tts_str_152:
    DEFM "OV", 0
tts_str_153:
    DEFM "^EN", 0
tts_str_154:
    DEFM "^I#", 0
tts_str_155:
    DEFM "OL", 0
tts_str_156:
    DEFM "OUGHT", 0
tts_str_157:
    DEFM "OUGH", 0
tts_str_158:
    DEFM "OU", 0
tts_str_159:
    DEFM "S#", 0
tts_str_160:
    DEFM "OUS", 0
tts_str_161:
    DEFM "OUR", 0
tts_str_162:
    DEFM "OULD", 0
tts_str_163:
    DEFM "^L", 0
tts_str_164:
    DEFM "OUP", 0
tts_str_165:
    DEFM "OY", 0
tts_str_166:
    DEFM "OING", 0
tts_str_167:
    DEFM "OI", 0
tts_str_168:
    DEFM "OOR", 0
tts_str_169:
    DEFM "OOK", 0
tts_str_170:
    DEFM "OOD", 0
tts_str_171:
    DEFM "OO", 0
tts_str_172:
    DEFM "OA", 0
tts_str_173:
    DEFM "ONLY", 0
tts_str_174:
    DEFM "ONCE", 0
tts_str_175:
    DEFM "ON'T", 0
tts_str_176:
    DEFM " :^", 0
tts_str_177:
    DEFM "ON", 0
tts_str_178:
    DEFM "#^", 0
tts_str_179:
    DEFM "ST ", 0
tts_str_180:
    DEFM "OTHER", 0
tts_str_181:
    DEFM "OSS", 0
tts_str_182:
    DEFM "OM", 0
tts_str_183:
    DEFM "PH", 0
tts_str_184:
    DEFM "PEOP", 0
tts_str_185:
    DEFM "POW", 0
tts_str_186:
    DEFM "PUT", 0
tts_str_187:
    DEFM "P", 0
tts_str_188:
    DEFM "QUAR", 0
tts_str_189:
    DEFM "QU", 0
tts_str_190:
    DEFM "Q", 0
tts_str_191:
    DEFM "RE", 0
tts_str_192:
    DEFM "SION", 0
tts_str_193:
    DEFM "SOME", 0
tts_str_194:
    DEFM "SUR", 0
tts_str_195:
    DEFM "SSU", 0
tts_str_196:
    DEFM "SED", 0
tts_str_197:
    DEFM "SAID", 0
tts_str_198:
    DEFM ".", 0
tts_str_199:
    DEFM "#:.E", 0
tts_str_200:
    DEFM "#:^##", 0
tts_str_201:
    DEFM "#:^#", 0
tts_str_202:
    DEFM "U", 0
tts_str_203:
    DEFM " :#", 0
tts_str_204:
    DEFM "SCH", 0
tts_str_205:
    DEFM "C+", 0
tts_str_206:
    DEFM "SM", 0
tts_str_207:
    DEFM "SN", 0
tts_str_208:
    DEFM "'", 0
tts_str_209:
    DEFM "THE", 0
tts_str_210:
    DEFM "TO", 0
tts_str_211:
    DEFM "THAT", 0
tts_str_212:
    DEFM "THIS", 0
tts_str_213:
    DEFM "THEY", 0
tts_str_214:
    DEFM "THERE", 0
tts_str_215:
    DEFM "THER", 0
tts_str_216:
    DEFM "THEIR", 0
tts_str_217:
    DEFM "THAN", 0
tts_str_218:
    DEFM "THEM", 0
tts_str_219:
    DEFM "THESE", 0
tts_str_220:
    DEFM "THEN", 0
tts_str_221:
    DEFM "THROUGH", 0
tts_str_222:
    DEFM "THOSE", 0
tts_str_223:
    DEFM "THOUGH", 0
tts_str_224:
    DEFM "THUS", 0
tts_str_225:
    DEFM "TED", 0
tts_str_226:
    DEFM "TI", 0
tts_str_227:
    DEFM "#N", 0
tts_str_228:
    DEFM "TIEN", 0
tts_str_229:
    DEFM "TUR", 0
tts_str_230:
    DEFM "TU", 0
tts_str_231:
    DEFM "TWO", 0
tts_str_232:
    DEFM "UN", 0
tts_str_233:
    DEFM "UPON", 0
tts_str_234:
    DEFM "UR", 0
tts_str_235:
    DEFM "^ ", 0
tts_str_236:
    DEFM "^^", 0
tts_str_237:
    DEFM "UY", 0
tts_str_238:
    DEFM " G", 0
tts_str_239:
    DEFM "VIEW", 0
tts_str_240:
    DEFM "V", 0
tts_str_241:
    DEFM "WERE", 0
tts_str_242:
    DEFM "WHERE", 0
tts_str_243:
    DEFM "WHAT", 0
tts_str_244:
    DEFM "WHOL", 0
tts_str_245:
    DEFM "WHO", 0
tts_str_246:
    DEFM "WH", 0
tts_str_247:
    DEFM "WAR", 0
tts_str_248:
    DEFM "WOR", 0
tts_str_249:
    DEFM "WR", 0
tts_str_250:
    DEFM "X", 0
tts_str_251:
    DEFM "YOUNG", 0
tts_str_252:
    DEFM "YOU", 0
tts_str_253:
    DEFM "YES", 0
tts_str_254:
    DEFM "Y", 0
tts_str_255:
    DEFM "0", 0
tts_str_256:
    DEFM "1", 0
tts_str_257:
    DEFM "2", 0
tts_str_258:
    DEFM "3", 0
tts_str_259:
    DEFM "4", 0
tts_str_260:
    DEFM "5", 0
tts_str_261:
    DEFM "6", 0
tts_str_262:
    DEFM "7", 0
tts_str_263:
    DEFM "8", 0
tts_str_264:
    DEFM "9", 0
tts_str_265:
    DEFM "--", 0
tts_str_266:
    DEFM "-", 0
tts_str_267:
    DEFM "'S", 0
tts_str_268:
    DEFM ",", 0
tts_str_269:
    DEFM "?", 0
tts_str_270:
    DEFM "!", 0
tts_str_271:
    DEFM "@", 0

; ------------------------------------------------------------
; Rule table
; Each entry: left(2), match(2), right(2), outlen(1), output(N)
; ANYTHING = 0x0001, NOMORE = 0x0003
; ------------------------------------------------------------
tts_rules:
    ; rule 0: ANYTHING [A] "NOTHING"
tts_rule_0:
    DEFW 0x0001
    DEFW tts_str_0
    DEFW tts_str_1
    DEFB 1
    DEFB 0x0F
    ; rule 1: "NOTHING" [ARE] "NOTHING"
tts_rule_1:
    DEFW tts_str_1
    DEFW tts_str_2
    DEFW tts_str_1
    DEFB 2
    DEFB 0x18, 0x0E
    ; rule 2: "NOTHING" [AR] "O"
tts_rule_2:
    DEFW tts_str_1
    DEFW tts_str_3
    DEFW tts_str_4
    DEFB 2
    DEFB 0x0F, 0x0E
    ; rule 3: ANYTHING [AR] "#"
tts_rule_3:
    DEFW 0x0001
    DEFW tts_str_3
    DEFW tts_str_5
    DEFB 2
    DEFB 0x07, 0x0E
    ; rule 4: "^" [AS] "#"
tts_rule_4:
    DEFW tts_str_6
    DEFW tts_str_7
    DEFW tts_str_5
    DEFB 2
    DEFB 0x14, 0x37
    ; rule 5: ANYTHING [A] "WA"
tts_rule_5:
    DEFW 0x0001
    DEFW tts_str_0
    DEFW tts_str_8
    DEFB 1
    DEFB 0x0F
    ; rule 6: ANYTHING [AW] ANYTHING
tts_rule_6:
    DEFW 0x0001
    DEFW tts_str_9
    DEFW 0x0001
    DEFB 1
    DEFB 0x17
    ; rule 7: " :" [ANY] ANYTHING
tts_rule_7:
    DEFW tts_str_10
    DEFW tts_str_11
    DEFW 0x0001
    DEFB 3
    DEFB 0x07, 0x0B, 0x13
    ; rule 8: ANYTHING [A] "^+#"
tts_rule_8:
    DEFW 0x0001
    DEFW tts_str_0
    DEFW tts_str_12
    DEFB 1
    DEFB 0x14
    ; rule 9: "#:" [ALLY] ANYTHING
tts_rule_9:
    DEFW tts_str_13
    DEFW tts_str_14
    DEFW 0x0001
    DEFB 3
    DEFB 0x0F, 0x2D, 0x13
    ; rule 10: "NOTHING" [AL] "#"
tts_rule_10:
    DEFW tts_str_1
    DEFW tts_str_15
    DEFW tts_str_5
    DEFB 2
    DEFB 0x0F, 0x2D
    ; rule 11: ANYTHING [AGAIN] ANYTHING
tts_rule_11:
    DEFW 0x0001
    DEFW tts_str_16
    DEFW 0x0001
    DEFB 4
    DEFB 0x0F, 0x3D, 0x07, 0x0B
    ; rule 12: "#:" [AG] "E"
tts_rule_12:
    DEFW tts_str_13
    DEFW tts_str_17
    DEFW tts_str_18
    DEFB 2
    DEFB 0x0C, 0x0A
    ; rule 13: ANYTHING [A] "^+:#"
tts_rule_13:
    DEFW 0x0001
    DEFW tts_str_0
    DEFW tts_str_19
    DEFB 1
    DEFB 0x1A
    ; rule 14: " :" [A] "^+ "
tts_rule_14:
    DEFW tts_str_10
    DEFW tts_str_0
    DEFW tts_str_20
    DEFB 1
    DEFB 0x14
    ; rule 15: ANYTHING [A] "^%"
tts_rule_15:
    DEFW 0x0001
    DEFW tts_str_0
    DEFW tts_str_21
    DEFB 1
    DEFB 0x14
    ; rule 16: "NOTHING" [ARR] ANYTHING
tts_rule_16:
    DEFW tts_str_1
    DEFW tts_str_22
    DEFW 0x0001
    DEFB 2
    DEFB 0x0F, 0x0E
    ; rule 17: ANYTHING [ARR] ANYTHING
tts_rule_17:
    DEFW 0x0001
    DEFW tts_str_22
    DEFW 0x0001
    DEFB 2
    DEFB 0x1A, 0x0E
    ; rule 18: " :" [AR] "NOTHING"
tts_rule_18:
    DEFW tts_str_10
    DEFW tts_str_3
    DEFW tts_str_1
    DEFB 2
    DEFB 0x18, 0x0E
    ; rule 19: ANYTHING [AR] "NOTHING"
tts_rule_19:
    DEFW 0x0001
    DEFW tts_str_3
    DEFW tts_str_1
    DEFB 1
    DEFB 0x33
    ; rule 20: ANYTHING [AR] ANYTHING
tts_rule_20:
    DEFW 0x0001
    DEFW tts_str_3
    DEFW 0x0001
    DEFB 2
    DEFB 0x18, 0x0E
    ; rule 21: ANYTHING [AIR] ANYTHING
tts_rule_21:
    DEFW 0x0001
    DEFW tts_str_23
    DEFW 0x0001
    DEFB 2
    DEFB 0x07, 0x0E
    ; rule 22: ANYTHING [AI] ANYTHING
tts_rule_22:
    DEFW 0x0001
    DEFW tts_str_24
    DEFW 0x0001
    DEFB 1
    DEFB 0x14
    ; rule 23: ANYTHING [AY] ANYTHING
tts_rule_23:
    DEFW 0x0001
    DEFW tts_str_25
    DEFW 0x0001
    DEFB 1
    DEFB 0x14
    ; rule 24: ANYTHING [AU] ANYTHING
tts_rule_24:
    DEFW 0x0001
    DEFW tts_str_26
    DEFW 0x0001
    DEFB 1
    DEFB 0x17
    ; rule 25: "#:" [AL] "NOTHING"
tts_rule_25:
    DEFW tts_str_13
    DEFW tts_str_15
    DEFW tts_str_1
    DEFB 2
    DEFB 0x0F, 0x2D
    ; rule 26: "#:" [ALS] "NOTHING"
tts_rule_26:
    DEFW tts_str_13
    DEFW tts_str_27
    DEFW tts_str_1
    DEFB 3
    DEFB 0x0F, 0x2D, 0x2B
    ; rule 27: ANYTHING [ALK] ANYTHING
tts_rule_27:
    DEFW 0x0001
    DEFW tts_str_28
    DEFW 0x0001
    DEFB 2
    DEFB 0x17, 0x2A
    ; rule 28: ANYTHING [AL] "^"
tts_rule_28:
    DEFW 0x0001
    DEFW tts_str_15
    DEFW tts_str_6
    DEFB 2
    DEFB 0x17, 0x2D
    ; rule 29: " :" [ABLE] ANYTHING
tts_rule_29:
    DEFW tts_str_10
    DEFW tts_str_29
    DEFW 0x0001
    DEFB 4
    DEFB 0x14, 0x1C, 0x0F, 0x2D
    ; rule 30: ANYTHING [ABLE] ANYTHING
tts_rule_30:
    DEFW 0x0001
    DEFW tts_str_29
    DEFW 0x0001
    DEFB 4
    DEFB 0x0F, 0x1C, 0x0F, 0x2D
    ; rule 31: ANYTHING [ANG] "+"
tts_rule_31:
    DEFW 0x0001
    DEFW tts_str_30
    DEFW tts_str_31
    DEFB 3
    DEFB 0x14, 0x0B, 0x0A
    ; rule 32: ANYTHING [A] ANYTHING
tts_rule_32:
    DEFW 0x0001
    DEFW tts_str_0
    DEFW 0x0001
    DEFB 1
    DEFB 0x1A
    ; rule 33: END
    DEFW 0x0003
    ; rule 34: "NOTHING" [BE] "^#"
tts_rule_34:
    DEFW tts_str_1
    DEFW tts_str_32
    DEFW tts_str_33
    DEFB 2
    DEFB 0x1C, 0x0C
    ; rule 35: ANYTHING [BEING] ANYTHING
tts_rule_35:
    DEFW 0x0001
    DEFW tts_str_34
    DEFW 0x0001
    DEFB 4
    DEFB 0x1C, 0x13, 0x0C, 0x2C
    ; rule 36: "NOTHING" [BOTH] "NOTHING"
tts_rule_36:
    DEFW tts_str_1
    DEFW tts_str_35
    DEFW tts_str_1
    DEFB 3
    DEFB 0x1C, 0x35, 0x1D
    ; rule 37: "NOTHING" [BUS] "#"
tts_rule_37:
    DEFW tts_str_1
    DEFW tts_str_36
    DEFW tts_str_5
    DEFB 3
    DEFB 0x1C, 0x0C, 0x2B
    ; rule 38: ANYTHING [BUIL] ANYTHING
tts_rule_38:
    DEFW 0x0001
    DEFW tts_str_37
    DEFW 0x0001
    DEFB 3
    DEFB 0x1C, 0x0C, 0x2D
    ; rule 39: ANYTHING [B] ANYTHING
tts_rule_39:
    DEFW 0x0001
    DEFW tts_str_38
    DEFW 0x0001
    DEFB 1
    DEFB 0x1C
    ; rule 40: END
    DEFW 0x0003
    ; rule 41: "NOTHING" [CH] "^"
tts_rule_41:
    DEFW tts_str_1
    DEFW tts_str_39
    DEFW tts_str_6
    DEFB 1
    DEFB 0x2A
    ; rule 42: "^E" [CH] ANYTHING
tts_rule_42:
    DEFW tts_str_40
    DEFW tts_str_39
    DEFW 0x0001
    DEFB 1
    DEFB 0x2A
    ; rule 43: ANYTHING [CH] ANYTHING
tts_rule_43:
    DEFW 0x0001
    DEFW tts_str_39
    DEFW 0x0001
    DEFB 1
    DEFB 0x32
    ; rule 44: " S" [CI] "#"
tts_rule_44:
    DEFW tts_str_41
    DEFW tts_str_42
    DEFW tts_str_5
    DEFB 2
    DEFB 0x37, 0x06
    ; rule 45: ANYTHING [CI] "A"
tts_rule_45:
    DEFW 0x0001
    DEFW tts_str_42
    DEFW tts_str_0
    DEFB 1
    DEFB 0x25
    ; rule 46: ANYTHING [CI] "O"
tts_rule_46:
    DEFW 0x0001
    DEFW tts_str_42
    DEFW tts_str_4
    DEFB 1
    DEFB 0x25
    ; rule 47: ANYTHING [CI] "EN"
tts_rule_47:
    DEFW 0x0001
    DEFW tts_str_42
    DEFW tts_str_43
    DEFB 1
    DEFB 0x25
    ; rule 48: ANYTHING [C] "+"
tts_rule_48:
    DEFW 0x0001
    DEFW tts_str_44
    DEFW tts_str_31
    DEFB 1
    DEFB 0x37
    ; rule 49: ANYTHING [CK] ANYTHING
tts_rule_49:
    DEFW 0x0001
    DEFW tts_str_45
    DEFW 0x0001
    DEFB 1
    DEFB 0x2A
    ; rule 50: ANYTHING [COM] "%"
tts_rule_50:
    DEFW 0x0001
    DEFW tts_str_46
    DEFW tts_str_47
    DEFB 4
    DEFB 0x2A, 0x0F, 0x0F, 0x10
    ; rule 51: ANYTHING [C] ANYTHING
tts_rule_51:
    DEFW 0x0001
    DEFW tts_str_44
    DEFW 0x0001
    DEFB 1
    DEFB 0x2A
    ; rule 52: END
    DEFW 0x0003
    ; rule 53: "#:" [DED] "NOTHING"
tts_rule_53:
    DEFW tts_str_13
    DEFW tts_str_48
    DEFW tts_str_1
    DEFB 3
    DEFB 0x15, 0x0C, 0x15
    ; rule 54: ".E" [D] "NOTHING"
tts_rule_54:
    DEFW tts_str_49
    DEFW tts_str_50
    DEFW tts_str_1
    DEFB 1
    DEFB 0x15
    ; rule 55: "#:^E" [D] "NOTHING"
tts_rule_55:
    DEFW tts_str_51
    DEFW tts_str_50
    DEFW tts_str_1
    DEFB 1
    DEFB 0x11
    ; rule 56: "NOTHING" [DE] "^#"
tts_rule_56:
    DEFW tts_str_1
    DEFW tts_str_52
    DEFW tts_str_33
    DEFB 2
    DEFB 0x15, 0x0C
    ; rule 57: "NOTHING" [DO] "NOTHING"
tts_rule_57:
    DEFW tts_str_1
    DEFW tts_str_53
    DEFW tts_str_1
    DEFB 2
    DEFB 0x15, 0x1F
    ; rule 58: "NOTHING" [DOES] ANYTHING
tts_rule_58:
    DEFW tts_str_1
    DEFW tts_str_54
    DEFW 0x0001
    DEFB 4
    DEFB 0x15, 0x0F, 0x0F, 0x2B
    ; rule 59: "NOTHING" [DOING] ANYTHING
tts_rule_59:
    DEFW tts_str_1
    DEFW tts_str_55
    DEFW 0x0001
    DEFB 4
    DEFB 0x15, 0x1F, 0x0C, 0x2C
    ; rule 60: "NOTHING" [DOW] ANYTHING
tts_rule_60:
    DEFW tts_str_1
    DEFW tts_str_56
    DEFW 0x0001
    DEFB 2
    DEFB 0x15, 0x20
    ; rule 61: ANYTHING [DU] "A"
tts_rule_61:
    DEFW 0x0001
    DEFW tts_str_57
    DEFW tts_str_0
    DEFB 2
    DEFB 0x0A, 0x1F
    ; rule 62: ANYTHING [D] ANYTHING
tts_rule_62:
    DEFW 0x0001
    DEFW tts_str_50
    DEFW 0x0001
    DEFB 1
    DEFB 0x15
    ; rule 63: END
    DEFW 0x0003
    ; rule 64: "#:" [E] "NOTHING"
tts_rule_64:
    DEFW tts_str_13
    DEFW tts_str_18
    DEFW tts_str_1
    DEFB 0
    ; rule 65: "':^" [E] "NOTHING"
tts_rule_65:
    DEFW tts_str_58
    DEFW tts_str_18
    DEFW tts_str_1
    DEFB 0
    ; rule 66: " :" [E] "NOTHING"
tts_rule_66:
    DEFW tts_str_10
    DEFW tts_str_18
    DEFW tts_str_1
    DEFB 1
    DEFB 0x13
    ; rule 67: "#" [ED] "NOTHING"
tts_rule_67:
    DEFW tts_str_5
    DEFW tts_str_59
    DEFW tts_str_1
    DEFB 1
    DEFB 0x15
    ; rule 68: "#:" [E] "D "
tts_rule_68:
    DEFW tts_str_13
    DEFW tts_str_18
    DEFW tts_str_60
    DEFB 0
    ; rule 69: ANYTHING [EV] "ER"
tts_rule_69:
    DEFW 0x0001
    DEFW tts_str_61
    DEFW tts_str_62
    DEFB 2
    DEFB 0x07, 0x23
    ; rule 70: ANYTHING [E] "^%"
tts_rule_70:
    DEFW 0x0001
    DEFW tts_str_18
    DEFW tts_str_21
    DEFB 1
    DEFB 0x13
    ; rule 71: ANYTHING [ERI] "#"
tts_rule_71:
    DEFW 0x0001
    DEFW tts_str_63
    DEFW tts_str_5
    DEFB 3
    DEFB 0x13, 0x0E, 0x13
    ; rule 72: ANYTHING [ERI] ANYTHING
tts_rule_72:
    DEFW 0x0001
    DEFW tts_str_63
    DEFW 0x0001
    DEFB 3
    DEFB 0x07, 0x0E, 0x0C
    ; rule 73: "#:" [ER] "#"
tts_rule_73:
    DEFW tts_str_13
    DEFW tts_str_62
    DEFW tts_str_5
    DEFB 1
    DEFB 0x33
    ; rule 74: ANYTHING [ER] "#"
tts_rule_74:
    DEFW 0x0001
    DEFW tts_str_62
    DEFW tts_str_5
    DEFB 2
    DEFB 0x07, 0x0E
    ; rule 75: ANYTHING [ER] ANYTHING
tts_rule_75:
    DEFW 0x0001
    DEFW tts_str_62
    DEFW 0x0001
    DEFB 1
    DEFB 0x33
    ; rule 76: "NOTHING" [EVEN] ANYTHING
tts_rule_76:
    DEFW tts_str_1
    DEFW tts_str_64
    DEFW 0x0001
    DEFB 4
    DEFB 0x13, 0x23, 0x07, 0x0B
    ; rule 77: "#:" [E] "W"
tts_rule_77:
    DEFW tts_str_13
    DEFW tts_str_18
    DEFW tts_str_65
    DEFB 0
    ; rule 78: "T" [EW] ANYTHING
tts_rule_78:
    DEFW tts_str_66
    DEFW tts_str_67
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 79: "S" [EW] ANYTHING
tts_rule_79:
    DEFW tts_str_68
    DEFW tts_str_67
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 80: "R" [EW] ANYTHING
tts_rule_80:
    DEFW tts_str_69
    DEFW tts_str_67
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 81: "D" [EW] ANYTHING
tts_rule_81:
    DEFW tts_str_50
    DEFW tts_str_67
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 82: "L" [EW] ANYTHING
tts_rule_82:
    DEFW tts_str_70
    DEFW tts_str_67
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 83: "Z" [EW] ANYTHING
tts_rule_83:
    DEFW tts_str_71
    DEFW tts_str_67
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 84: "N" [EW] ANYTHING
tts_rule_84:
    DEFW tts_str_72
    DEFW tts_str_67
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 85: "J" [EW] ANYTHING
tts_rule_85:
    DEFW tts_str_73
    DEFW tts_str_67
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 86: "TH" [EW] ANYTHING
tts_rule_86:
    DEFW tts_str_74
    DEFW tts_str_67
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 87: "CH" [EW] ANYTHING
tts_rule_87:
    DEFW tts_str_39
    DEFW tts_str_67
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 88: "SH" [EW] ANYTHING
tts_rule_88:
    DEFW tts_str_75
    DEFW tts_str_67
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 89: ANYTHING [EW] ANYTHING
tts_rule_89:
    DEFW 0x0001
    DEFW tts_str_67
    DEFW 0x0001
    DEFB 2
    DEFB 0x31, 0x1F
    ; rule 90: ANYTHING [E] "O"
tts_rule_90:
    DEFW 0x0001
    DEFW tts_str_18
    DEFW tts_str_4
    DEFB 1
    DEFB 0x13
    ; rule 91: "#:S" [ES] "NOTHING"
tts_rule_91:
    DEFW tts_str_76
    DEFW tts_str_77
    DEFW tts_str_1
    DEFB 2
    DEFB 0x0C, 0x2B
    ; rule 92: "#:C" [ES] "NOTHING"
tts_rule_92:
    DEFW tts_str_78
    DEFW tts_str_77
    DEFW tts_str_1
    DEFB 2
    DEFB 0x0C, 0x2B
    ; rule 93: "#:G" [ES] "NOTHING"
tts_rule_93:
    DEFW tts_str_79
    DEFW tts_str_77
    DEFW tts_str_1
    DEFB 2
    DEFB 0x0C, 0x2B
    ; rule 94: "#:Z" [ES] "NOTHING"
tts_rule_94:
    DEFW tts_str_80
    DEFW tts_str_77
    DEFW tts_str_1
    DEFB 2
    DEFB 0x0C, 0x2B
    ; rule 95: "#:X" [ES] "NOTHING"
tts_rule_95:
    DEFW tts_str_81
    DEFW tts_str_77
    DEFW tts_str_1
    DEFB 2
    DEFB 0x0C, 0x2B
    ; rule 96: "#:J" [ES] "NOTHING"
tts_rule_96:
    DEFW tts_str_82
    DEFW tts_str_77
    DEFW tts_str_1
    DEFB 2
    DEFB 0x0C, 0x2B
    ; rule 97: "#:CH" [ES] "NOTHING"
tts_rule_97:
    DEFW tts_str_83
    DEFW tts_str_77
    DEFW tts_str_1
    DEFB 2
    DEFB 0x0C, 0x2B
    ; rule 98: "#:SH" [ES] "NOTHING"
tts_rule_98:
    DEFW tts_str_84
    DEFW tts_str_77
    DEFW tts_str_1
    DEFB 2
    DEFB 0x0C, 0x2B
    ; rule 99: "#:" [E] "S "
tts_rule_99:
    DEFW tts_str_13
    DEFW tts_str_18
    DEFW tts_str_85
    DEFB 0
    ; rule 100: "#:" [ELY] "NOTHING"
tts_rule_100:
    DEFW tts_str_13
    DEFW tts_str_86
    DEFW tts_str_1
    DEFB 2
    DEFB 0x2D, 0x13
    ; rule 101: "#:" [EMENT] ANYTHING
tts_rule_101:
    DEFW tts_str_13
    DEFW tts_str_87
    DEFW 0x0001
    DEFB 4
    DEFB 0x10, 0x07, 0x0B, 0x11
    ; rule 102: ANYTHING [EFUL] ANYTHING
tts_rule_102:
    DEFW 0x0001
    DEFW tts_str_88
    DEFW 0x0001
    DEFB 3
    DEFB 0x28, 0x1E, 0x2D
    ; rule 103: ANYTHING [EE] ANYTHING
tts_rule_103:
    DEFW 0x0001
    DEFW tts_str_89
    DEFW 0x0001
    DEFB 1
    DEFB 0x13
    ; rule 104: ANYTHING [EARN] ANYTHING
tts_rule_104:
    DEFW 0x0001
    DEFW tts_str_90
    DEFW 0x0001
    DEFB 2
    DEFB 0x33, 0x0B
    ; rule 105: "NOTHING" [EAR] "^"
tts_rule_105:
    DEFW tts_str_1
    DEFW tts_str_91
    DEFW tts_str_6
    DEFB 1
    DEFB 0x33
    ; rule 106: ANYTHING [EAD] ANYTHING
tts_rule_106:
    DEFW 0x0001
    DEFW tts_str_92
    DEFW 0x0001
    DEFB 2
    DEFB 0x07, 0x15
    ; rule 107: "#:" [EA] "NOTHING"
tts_rule_107:
    DEFW tts_str_13
    DEFW tts_str_93
    DEFW tts_str_1
    DEFB 2
    DEFB 0x13, 0x0F
    ; rule 108: ANYTHING [EA] "SU"
tts_rule_108:
    DEFW 0x0001
    DEFW tts_str_93
    DEFW tts_str_94
    DEFB 1
    DEFB 0x07
    ; rule 109: ANYTHING [EA] ANYTHING
tts_rule_109:
    DEFW 0x0001
    DEFW tts_str_93
    DEFW 0x0001
    DEFB 1
    DEFB 0x13
    ; rule 110: ANYTHING [EIGH] ANYTHING
tts_rule_110:
    DEFW 0x0001
    DEFW tts_str_95
    DEFW 0x0001
    DEFB 1
    DEFB 0x14
    ; rule 111: ANYTHING [EI] ANYTHING
tts_rule_111:
    DEFW 0x0001
    DEFW tts_str_96
    DEFW 0x0001
    DEFB 1
    DEFB 0x13
    ; rule 112: "NOTHING" [EYE] ANYTHING
tts_rule_112:
    DEFW tts_str_1
    DEFW tts_str_97
    DEFW 0x0001
    DEFB 1
    DEFB 0x06
    ; rule 113: ANYTHING [EY] ANYTHING
tts_rule_113:
    DEFW 0x0001
    DEFW tts_str_98
    DEFW 0x0001
    DEFB 1
    DEFB 0x13
    ; rule 114: ANYTHING [EU] ANYTHING
tts_rule_114:
    DEFW 0x0001
    DEFW tts_str_99
    DEFW 0x0001
    DEFB 2
    DEFB 0x31, 0x1F
    ; rule 115: ANYTHING [E] ANYTHING
tts_rule_115:
    DEFW 0x0001
    DEFW tts_str_18
    DEFW 0x0001
    DEFB 1
    DEFB 0x07
    ; rule 116: END
    DEFW 0x0003
    ; rule 117: ANYTHING [FUL] ANYTHING
tts_rule_117:
    DEFW 0x0001
    DEFW tts_str_100
    DEFW 0x0001
    DEFB 3
    DEFB 0x28, 0x1E, 0x2D
    ; rule 118: ANYTHING [F] ANYTHING
tts_rule_118:
    DEFW 0x0001
    DEFW tts_str_101
    DEFW 0x0001
    DEFB 1
    DEFB 0x28
    ; rule 119: END
    DEFW 0x0003
    ; rule 120: ANYTHING [GIV] ANYTHING
tts_rule_120:
    DEFW 0x0001
    DEFW tts_str_102
    DEFW 0x0001
    DEFB 3
    DEFB 0x3D, 0x0C, 0x23
    ; rule 121: "NOTHING" [G] "I^"
tts_rule_121:
    DEFW tts_str_1
    DEFW tts_str_103
    DEFW tts_str_104
    DEFB 1
    DEFB 0x3D
    ; rule 122: ANYTHING [GE] "T"
tts_rule_122:
    DEFW 0x0001
    DEFW tts_str_105
    DEFW tts_str_66
    DEFB 2
    DEFB 0x3D, 0x07
    ; rule 123: "SU" [GGES] ANYTHING
tts_rule_123:
    DEFW tts_str_94
    DEFW tts_str_106
    DEFW 0x0001
    DEFB 4
    DEFB 0x3D, 0x0A, 0x07, 0x37
    ; rule 124: ANYTHING [GG] ANYTHING
tts_rule_124:
    DEFW 0x0001
    DEFW tts_str_107
    DEFW 0x0001
    DEFB 1
    DEFB 0x3D
    ; rule 125: " B#" [G] ANYTHING
tts_rule_125:
    DEFW tts_str_108
    DEFW tts_str_103
    DEFW 0x0001
    DEFB 1
    DEFB 0x3D
    ; rule 126: ANYTHING [G] "+"
tts_rule_126:
    DEFW 0x0001
    DEFW tts_str_103
    DEFW tts_str_31
    DEFB 1
    DEFB 0x0A
    ; rule 127: ANYTHING [GREAT] ANYTHING
tts_rule_127:
    DEFW 0x0001
    DEFW tts_str_109
    DEFW 0x0001
    DEFB 4
    DEFB 0x3D, 0x0E, 0x14, 0x11
    ; rule 128: "#" [GH] ANYTHING
tts_rule_128:
    DEFW tts_str_5
    DEFW tts_str_110
    DEFW 0x0001
    DEFB 0
    ; rule 129: ANYTHING [G] ANYTHING
tts_rule_129:
    DEFW 0x0001
    DEFW tts_str_103
    DEFW 0x0001
    DEFB 1
    DEFB 0x3D
    ; rule 130: END
    DEFW 0x0003
    ; rule 131: "NOTHING" [HAV] ANYTHING
tts_rule_131:
    DEFW tts_str_1
    DEFW tts_str_111
    DEFW 0x0001
    DEFB 3
    DEFB 0x1B, 0x1A, 0x23
    ; rule 132: "NOTHING" [HERE] ANYTHING
tts_rule_132:
    DEFW tts_str_1
    DEFW tts_str_112
    DEFW 0x0001
    DEFB 3
    DEFB 0x1B, 0x13, 0x0E
    ; rule 133: "NOTHING" [HOUR] ANYTHING
tts_rule_133:
    DEFW tts_str_1
    DEFW tts_str_113
    DEFW 0x0001
    DEFB 2
    DEFB 0x20, 0x33
    ; rule 134: ANYTHING [HOW] ANYTHING
tts_rule_134:
    DEFW 0x0001
    DEFW tts_str_114
    DEFW 0x0001
    DEFB 2
    DEFB 0x1B, 0x20
    ; rule 135: ANYTHING [H] "#"
tts_rule_135:
    DEFW 0x0001
    DEFW tts_str_115
    DEFW tts_str_5
    DEFB 1
    DEFB 0x1B
    ; rule 136: ANYTHING [H] ANYTHING
tts_rule_136:
    DEFW 0x0001
    DEFW tts_str_115
    DEFW 0x0001
    DEFB 0
    ; rule 137: END
    DEFW 0x0003
    ; rule 138: "NOTHING" [IN] ANYTHING
tts_rule_138:
    DEFW tts_str_1
    DEFW tts_str_116
    DEFW 0x0001
    DEFB 2
    DEFB 0x0C, 0x0B
    ; rule 139: "NOTHING" [I] "NOTHING"
tts_rule_139:
    DEFW tts_str_1
    DEFW tts_str_117
    DEFW tts_str_1
    DEFB 1
    DEFB 0x06
    ; rule 140: ANYTHING [IN] "D"
tts_rule_140:
    DEFW 0x0001
    DEFW tts_str_116
    DEFW tts_str_50
    DEFB 2
    DEFB 0x06, 0x0B
    ; rule 141: ANYTHING [IER] ANYTHING
tts_rule_141:
    DEFW 0x0001
    DEFW tts_str_118
    DEFW 0x0001
    DEFB 2
    DEFB 0x13, 0x33
    ; rule 142: "#:R" [IED] ANYTHING
tts_rule_142:
    DEFW tts_str_119
    DEFW tts_str_120
    DEFW 0x0001
    DEFB 2
    DEFB 0x13, 0x15
    ; rule 143: ANYTHING [IED] "NOTHING"
tts_rule_143:
    DEFW 0x0001
    DEFW tts_str_120
    DEFW tts_str_1
    DEFB 2
    DEFB 0x06, 0x15
    ; rule 144: ANYTHING [IEN] ANYTHING
tts_rule_144:
    DEFW 0x0001
    DEFW tts_str_121
    DEFW 0x0001
    DEFB 3
    DEFB 0x13, 0x07, 0x0B
    ; rule 145: ANYTHING [IE] "T"
tts_rule_145:
    DEFW 0x0001
    DEFW tts_str_122
    DEFW tts_str_66
    DEFB 2
    DEFB 0x06, 0x07
    ; rule 146: " :" [I] "%"
tts_rule_146:
    DEFW tts_str_10
    DEFW tts_str_117
    DEFW tts_str_47
    DEFB 1
    DEFB 0x06
    ; rule 147: ANYTHING [I] "%"
tts_rule_147:
    DEFW 0x0001
    DEFW tts_str_117
    DEFW tts_str_47
    DEFB 1
    DEFB 0x13
    ; rule 148: ANYTHING [IE] ANYTHING
tts_rule_148:
    DEFW 0x0001
    DEFW tts_str_122
    DEFW 0x0001
    DEFB 1
    DEFB 0x13
    ; rule 149: ANYTHING [I] "^+:#"
tts_rule_149:
    DEFW 0x0001
    DEFW tts_str_117
    DEFW tts_str_19
    DEFB 1
    DEFB 0x0C
    ; rule 150: ANYTHING [IR] "#"
tts_rule_150:
    DEFW 0x0001
    DEFW tts_str_123
    DEFW tts_str_5
    DEFB 2
    DEFB 0x06, 0x0E
    ; rule 151: ANYTHING [IZ] "%"
tts_rule_151:
    DEFW 0x0001
    DEFW tts_str_124
    DEFW tts_str_47
    DEFB 2
    DEFB 0x06, 0x2B
    ; rule 152: ANYTHING [IS] "%"
tts_rule_152:
    DEFW 0x0001
    DEFW tts_str_125
    DEFW tts_str_47
    DEFB 2
    DEFB 0x06, 0x2B
    ; rule 153: ANYTHING [I] "D%"
tts_rule_153:
    DEFW 0x0001
    DEFW tts_str_117
    DEFW tts_str_126
    DEFB 1
    DEFB 0x06
    ; rule 154: "+^" [I] "^+"
tts_rule_154:
    DEFW tts_str_127
    DEFW tts_str_117
    DEFW tts_str_128
    DEFB 1
    DEFB 0x0C
    ; rule 155: ANYTHING [I] "T%"
tts_rule_155:
    DEFW 0x0001
    DEFW tts_str_117
    DEFW tts_str_129
    DEFB 1
    DEFB 0x06
    ; rule 156: "#:^" [I] "^+"
tts_rule_156:
    DEFW tts_str_130
    DEFW tts_str_117
    DEFW tts_str_128
    DEFB 1
    DEFB 0x0C
    ; rule 157: ANYTHING [I] "^+"
tts_rule_157:
    DEFW 0x0001
    DEFW tts_str_117
    DEFW tts_str_128
    DEFB 1
    DEFB 0x06
    ; rule 158: ANYTHING [IR] ANYTHING
tts_rule_158:
    DEFW 0x0001
    DEFW tts_str_123
    DEFW 0x0001
    DEFB 1
    DEFB 0x33
    ; rule 159: ANYTHING [IGH] ANYTHING
tts_rule_159:
    DEFW 0x0001
    DEFW tts_str_131
    DEFW 0x0001
    DEFB 1
    DEFB 0x06
    ; rule 160: ANYTHING [ILD] ANYTHING
tts_rule_160:
    DEFW 0x0001
    DEFW tts_str_132
    DEFW 0x0001
    DEFB 3
    DEFB 0x06, 0x2D, 0x15
    ; rule 161: ANYTHING [IGN] "NOTHING"
tts_rule_161:
    DEFW 0x0001
    DEFW tts_str_133
    DEFW tts_str_1
    DEFB 2
    DEFB 0x06, 0x0B
    ; rule 162: ANYTHING [IGN] "^"
tts_rule_162:
    DEFW 0x0001
    DEFW tts_str_133
    DEFW tts_str_6
    DEFB 2
    DEFB 0x06, 0x0B
    ; rule 163: ANYTHING [IGN] "%"
tts_rule_163:
    DEFW 0x0001
    DEFW tts_str_133
    DEFW tts_str_47
    DEFB 2
    DEFB 0x06, 0x0B
    ; rule 164: ANYTHING [IQUE] ANYTHING
tts_rule_164:
    DEFW 0x0001
    DEFW tts_str_134
    DEFW 0x0001
    DEFB 2
    DEFB 0x13, 0x2A
    ; rule 165: ANYTHING [I] ANYTHING
tts_rule_165:
    DEFW 0x0001
    DEFW tts_str_117
    DEFW 0x0001
    DEFB 1
    DEFB 0x0C
    ; rule 166: END
    DEFW 0x0003
    ; rule 167: ANYTHING [J] ANYTHING
tts_rule_167:
    DEFW 0x0001
    DEFW tts_str_73
    DEFW 0x0001
    DEFB 1
    DEFB 0x0A
    ; rule 168: END
    DEFW 0x0003
    ; rule 169: "NOTHING" [K] "N"
tts_rule_169:
    DEFW tts_str_1
    DEFW tts_str_135
    DEFW tts_str_72
    DEFB 0
    ; rule 170: ANYTHING [K] ANYTHING
tts_rule_170:
    DEFW 0x0001
    DEFW tts_str_135
    DEFW 0x0001
    DEFB 1
    DEFB 0x2A
    ; rule 171: END
    DEFW 0x0003
    ; rule 172: ANYTHING [LO] "C#"
tts_rule_172:
    DEFW 0x0001
    DEFW tts_str_136
    DEFW tts_str_137
    DEFB 2
    DEFB 0x2D, 0x35
    ; rule 173: "L" [L] ANYTHING
tts_rule_173:
    DEFW tts_str_70
    DEFW tts_str_70
    DEFW 0x0001
    DEFB 0
    ; rule 174: "#:^" [L] "%"
tts_rule_174:
    DEFW tts_str_130
    DEFW tts_str_70
    DEFW tts_str_47
    DEFB 2
    DEFB 0x0F, 0x2D
    ; rule 175: ANYTHING [LEAD] ANYTHING
tts_rule_175:
    DEFW 0x0001
    DEFW tts_str_138
    DEFW 0x0001
    DEFB 3
    DEFB 0x2D, 0x13, 0x15
    ; rule 176: ANYTHING [L] ANYTHING
tts_rule_176:
    DEFW 0x0001
    DEFW tts_str_70
    DEFW 0x0001
    DEFB 1
    DEFB 0x2D
    ; rule 177: END
    DEFW 0x0003
    ; rule 178: ANYTHING [MOV] ANYTHING
tts_rule_178:
    DEFW 0x0001
    DEFW tts_str_139
    DEFW 0x0001
    DEFB 3
    DEFB 0x10, 0x1F, 0x23
    ; rule 179: ANYTHING [M] ANYTHING
tts_rule_179:
    DEFW 0x0001
    DEFW tts_str_140
    DEFW 0x0001
    DEFB 1
    DEFB 0x10
    ; rule 180: END
    DEFW 0x0003
    ; rule 181: "E" [NG] "+"
tts_rule_181:
    DEFW tts_str_18
    DEFW tts_str_141
    DEFW tts_str_31
    DEFB 2
    DEFB 0x0B, 0x0A
    ; rule 182: ANYTHING [NG] "R"
tts_rule_182:
    DEFW 0x0001
    DEFW tts_str_141
    DEFW tts_str_69
    DEFB 2
    DEFB 0x2C, 0x3D
    ; rule 183: ANYTHING [NG] "#"
tts_rule_183:
    DEFW 0x0001
    DEFW tts_str_141
    DEFW tts_str_5
    DEFB 2
    DEFB 0x2C, 0x3D
    ; rule 184: ANYTHING [NGL] "%"
tts_rule_184:
    DEFW 0x0001
    DEFW tts_str_142
    DEFW tts_str_47
    DEFB 4
    DEFB 0x2C, 0x3D, 0x0F, 0x2D
    ; rule 185: ANYTHING [NG] ANYTHING
tts_rule_185:
    DEFW 0x0001
    DEFW tts_str_141
    DEFW 0x0001
    DEFB 1
    DEFB 0x2C
    ; rule 186: ANYTHING [NK] ANYTHING
tts_rule_186:
    DEFW 0x0001
    DEFW tts_str_143
    DEFW 0x0001
    DEFB 2
    DEFB 0x2C, 0x2A
    ; rule 187: "NOTHING" [NOW] "NOTHING"
tts_rule_187:
    DEFW tts_str_1
    DEFW tts_str_144
    DEFW tts_str_1
    DEFB 2
    DEFB 0x0B, 0x20
    ; rule 188: ANYTHING [N] ANYTHING
tts_rule_188:
    DEFW 0x0001
    DEFW tts_str_72
    DEFW 0x0001
    DEFB 1
    DEFB 0x0B
    ; rule 189: END
    DEFW 0x0003
    ; rule 190: ANYTHING [OF] "NOTHING"
tts_rule_190:
    DEFW 0x0001
    DEFW tts_str_145
    DEFW tts_str_1
    DEFB 2
    DEFB 0x0F, 0x23
    ; rule 191: ANYTHING [OROUGH] ANYTHING
tts_rule_191:
    DEFW 0x0001
    DEFW tts_str_146
    DEFW 0x0001
    DEFB 2
    DEFB 0x33, 0x35
    ; rule 192: "#:" [OR] "NOTHING"
tts_rule_192:
    DEFW tts_str_13
    DEFW tts_str_147
    DEFW tts_str_1
    DEFB 1
    DEFB 0x33
    ; rule 193: "#:" [ORS] "NOTHING"
tts_rule_193:
    DEFW tts_str_13
    DEFW tts_str_148
    DEFW tts_str_1
    DEFB 2
    DEFB 0x33, 0x2B
    ; rule 194: ANYTHING [OR] ANYTHING
tts_rule_194:
    DEFW 0x0001
    DEFW tts_str_147
    DEFW 0x0001
    DEFB 2
    DEFB 0x17, 0x0E
    ; rule 195: "NOTHING" [ONE] ANYTHING
tts_rule_195:
    DEFW tts_str_1
    DEFW tts_str_149
    DEFW 0x0001
    DEFB 4
    DEFB 0x2E, 0x0F, 0x0F, 0x0B
    ; rule 196: "NOTHING" [OW] ANYTHING
tts_rule_196:
    DEFW tts_str_1
    DEFW tts_str_150
    DEFW 0x0001
    DEFB 1
    DEFB 0x35
    ; rule 197: ANYTHING [OW] ANYTHING
tts_rule_197:
    DEFW 0x0001
    DEFW tts_str_150
    DEFW 0x0001
    DEFB 1
    DEFB 0x35
    ; rule 198: "NOTHING" [OVER] ANYTHING
tts_rule_198:
    DEFW tts_str_1
    DEFW tts_str_151
    DEFW 0x0001
    DEFB 3
    DEFB 0x35, 0x23, 0x33
    ; rule 199: ANYTHING [OV] ANYTHING
tts_rule_199:
    DEFW 0x0001
    DEFW tts_str_152
    DEFW 0x0001
    DEFB 3
    DEFB 0x0F, 0x0F, 0x23
    ; rule 200: ANYTHING [O] "^%"
tts_rule_200:
    DEFW 0x0001
    DEFW tts_str_4
    DEFW tts_str_21
    DEFB 1
    DEFB 0x35
    ; rule 201: ANYTHING [O] "^EN"
tts_rule_201:
    DEFW 0x0001
    DEFW tts_str_4
    DEFW tts_str_153
    DEFB 1
    DEFB 0x35
    ; rule 202: ANYTHING [O] "^I#"
tts_rule_202:
    DEFW 0x0001
    DEFW tts_str_4
    DEFW tts_str_154
    DEFB 1
    DEFB 0x35
    ; rule 203: ANYTHING [OL] "D"
tts_rule_203:
    DEFW 0x0001
    DEFW tts_str_155
    DEFW tts_str_50
    DEFB 2
    DEFB 0x35, 0x2D
    ; rule 204: ANYTHING [OUGHT] ANYTHING
tts_rule_204:
    DEFW 0x0001
    DEFW tts_str_156
    DEFW 0x0001
    DEFB 2
    DEFB 0x17, 0x11
    ; rule 205: ANYTHING [OUGH] ANYTHING
tts_rule_205:
    DEFW 0x0001
    DEFW tts_str_157
    DEFW 0x0001
    DEFB 3
    DEFB 0x0F, 0x0F, 0x28
    ; rule 206: "NOTHING" [OU] ANYTHING
tts_rule_206:
    DEFW tts_str_1
    DEFW tts_str_158
    DEFW 0x0001
    DEFB 1
    DEFB 0x20
    ; rule 207: "H" [OU] "S#"
tts_rule_207:
    DEFW tts_str_115
    DEFW tts_str_158
    DEFW tts_str_159
    DEFB 1
    DEFB 0x20
    ; rule 208: ANYTHING [OUS] ANYTHING
tts_rule_208:
    DEFW 0x0001
    DEFW tts_str_160
    DEFW 0x0001
    DEFB 2
    DEFB 0x0F, 0x37
    ; rule 209: ANYTHING [OUR] ANYTHING
tts_rule_209:
    DEFW 0x0001
    DEFW tts_str_161
    DEFW 0x0001
    DEFB 2
    DEFB 0x17, 0x0E
    ; rule 210: ANYTHING [OULD] ANYTHING
tts_rule_210:
    DEFW 0x0001
    DEFW tts_str_162
    DEFW 0x0001
    DEFB 2
    DEFB 0x1E, 0x15
    ; rule 211: "^" [OU] "^L"
tts_rule_211:
    DEFW tts_str_6
    DEFW tts_str_158
    DEFW tts_str_163
    DEFB 2
    DEFB 0x0F, 0x0F
    ; rule 212: ANYTHING [OUP] ANYTHING
tts_rule_212:
    DEFW 0x0001
    DEFW tts_str_164
    DEFW 0x0001
    DEFB 2
    DEFB 0x1F, 0x09
    ; rule 213: ANYTHING [OU] ANYTHING
tts_rule_213:
    DEFW 0x0001
    DEFW tts_str_158
    DEFW 0x0001
    DEFB 1
    DEFB 0x20
    ; rule 214: ANYTHING [OY] ANYTHING
tts_rule_214:
    DEFW 0x0001
    DEFW tts_str_165
    DEFW 0x0001
    DEFB 1
    DEFB 0x05
    ; rule 215: ANYTHING [OING] ANYTHING
tts_rule_215:
    DEFW 0x0001
    DEFW tts_str_166
    DEFW 0x0001
    DEFB 3
    DEFB 0x35, 0x0C, 0x2C
    ; rule 216: ANYTHING [OI] ANYTHING
tts_rule_216:
    DEFW 0x0001
    DEFW tts_str_167
    DEFW 0x0001
    DEFB 1
    DEFB 0x05
    ; rule 217: ANYTHING [OOR] ANYTHING
tts_rule_217:
    DEFW 0x0001
    DEFW tts_str_168
    DEFW 0x0001
    DEFB 2
    DEFB 0x17, 0x0E
    ; rule 218: ANYTHING [OOK] ANYTHING
tts_rule_218:
    DEFW 0x0001
    DEFW tts_str_169
    DEFW 0x0001
    DEFB 2
    DEFB 0x1E, 0x2A
    ; rule 219: ANYTHING [OOD] ANYTHING
tts_rule_219:
    DEFW 0x0001
    DEFW tts_str_170
    DEFW 0x0001
    DEFB 2
    DEFB 0x1E, 0x15
    ; rule 220: ANYTHING [OO] ANYTHING
tts_rule_220:
    DEFW 0x0001
    DEFW tts_str_171
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 221: ANYTHING [O] "E"
tts_rule_221:
    DEFW 0x0001
    DEFW tts_str_4
    DEFW tts_str_18
    DEFB 1
    DEFB 0x35
    ; rule 222: ANYTHING [O] "NOTHING"
tts_rule_222:
    DEFW 0x0001
    DEFW tts_str_4
    DEFW tts_str_1
    DEFB 1
    DEFB 0x35
    ; rule 223: ANYTHING [OA] ANYTHING
tts_rule_223:
    DEFW 0x0001
    DEFW tts_str_172
    DEFW 0x0001
    DEFB 1
    DEFB 0x35
    ; rule 224: "NOTHING" [ONLY] ANYTHING
tts_rule_224:
    DEFW tts_str_1
    DEFW tts_str_173
    DEFW 0x0001
    DEFB 4
    DEFB 0x35, 0x0B, 0x2D, 0x13
    ; rule 225: "NOTHING" [ONCE] ANYTHING
tts_rule_225:
    DEFW tts_str_1
    DEFW tts_str_174
    DEFW 0x0001
    DEFB 5
    DEFB 0x2E, 0x0F, 0x0F, 0x0B, 0x37
    ; rule 226: ANYTHING [ON'T] ANYTHING
tts_rule_226:
    DEFW 0x0001
    DEFW tts_str_175
    DEFW 0x0001
    DEFB 3
    DEFB 0x35, 0x0B, 0x11
    ; rule 227: "C" [O] "N"
tts_rule_227:
    DEFW tts_str_44
    DEFW tts_str_4
    DEFW tts_str_72
    DEFB 1
    DEFB 0x18
    ; rule 228: ANYTHING [O] "NG"
tts_rule_228:
    DEFW 0x0001
    DEFW tts_str_4
    DEFW tts_str_141
    DEFB 1
    DEFB 0x17
    ; rule 229: " :^" [O] "N"
tts_rule_229:
    DEFW tts_str_176
    DEFW tts_str_4
    DEFW tts_str_72
    DEFB 2
    DEFB 0x0F, 0x0F
    ; rule 230: "I" [ON] ANYTHING
tts_rule_230:
    DEFW tts_str_117
    DEFW tts_str_177
    DEFW 0x0001
    DEFB 2
    DEFB 0x0F, 0x0B
    ; rule 231: "#:" [ON] "NOTHING"
tts_rule_231:
    DEFW tts_str_13
    DEFW tts_str_177
    DEFW tts_str_1
    DEFB 2
    DEFB 0x0F, 0x0B
    ; rule 232: "#^" [ON] ANYTHING
tts_rule_232:
    DEFW tts_str_178
    DEFW tts_str_177
    DEFW 0x0001
    DEFB 2
    DEFB 0x0F, 0x0B
    ; rule 233: ANYTHING [O] "ST "
tts_rule_233:
    DEFW 0x0001
    DEFW tts_str_4
    DEFW tts_str_179
    DEFB 1
    DEFB 0x35
    ; rule 234: ANYTHING [OF] "^"
tts_rule_234:
    DEFW 0x0001
    DEFW tts_str_145
    DEFW tts_str_6
    DEFB 2
    DEFB 0x17, 0x28
    ; rule 235: ANYTHING [OTHER] ANYTHING
tts_rule_235:
    DEFW 0x0001
    DEFW tts_str_180
    DEFW 0x0001
    DEFB 4
    DEFB 0x0F, 0x0F, 0x12, 0x33
    ; rule 236: ANYTHING [OSS] "NOTHING"
tts_rule_236:
    DEFW 0x0001
    DEFW tts_str_181
    DEFW tts_str_1
    DEFB 2
    DEFB 0x17, 0x37
    ; rule 237: "#:^" [OM] ANYTHING
tts_rule_237:
    DEFW tts_str_130
    DEFW tts_str_182
    DEFW 0x0001
    DEFB 3
    DEFB 0x0F, 0x0F, 0x10
    ; rule 238: ANYTHING [O] ANYTHING
tts_rule_238:
    DEFW 0x0001
    DEFW tts_str_4
    DEFW 0x0001
    DEFB 1
    DEFB 0x18
    ; rule 239: END
    DEFW 0x0003
    ; rule 240: ANYTHING [PH] ANYTHING
tts_rule_240:
    DEFW 0x0001
    DEFW tts_str_183
    DEFW 0x0001
    DEFB 1
    DEFB 0x28
    ; rule 241: ANYTHING [PEOP] ANYTHING
tts_rule_241:
    DEFW 0x0001
    DEFW tts_str_184
    DEFW 0x0001
    DEFB 3
    DEFB 0x09, 0x13, 0x09
    ; rule 242: ANYTHING [POW] ANYTHING
tts_rule_242:
    DEFW 0x0001
    DEFW tts_str_185
    DEFW 0x0001
    DEFB 2
    DEFB 0x09, 0x20
    ; rule 243: ANYTHING [PUT] "NOTHING"
tts_rule_243:
    DEFW 0x0001
    DEFW tts_str_186
    DEFW tts_str_1
    DEFB 3
    DEFB 0x09, 0x1E, 0x11
    ; rule 244: ANYTHING [P] ANYTHING
tts_rule_244:
    DEFW 0x0001
    DEFW tts_str_187
    DEFW 0x0001
    DEFB 1
    DEFB 0x09
    ; rule 245: END
    DEFW 0x0003
    ; rule 246: ANYTHING [QUAR] ANYTHING
tts_rule_246:
    DEFW 0x0001
    DEFW tts_str_188
    DEFW 0x0001
    DEFB 4
    DEFB 0x2A, 0x2E, 0x17, 0x0E
    ; rule 247: ANYTHING [QU] ANYTHING
tts_rule_247:
    DEFW 0x0001
    DEFW tts_str_189
    DEFW 0x0001
    DEFB 2
    DEFB 0x2A, 0x2E
    ; rule 248: ANYTHING [Q] ANYTHING
tts_rule_248:
    DEFW 0x0001
    DEFW tts_str_190
    DEFW 0x0001
    DEFB 1
    DEFB 0x2A
    ; rule 249: END
    DEFW 0x0003
    ; rule 250: "NOTHING" [RE] "^#"
tts_rule_250:
    DEFW tts_str_1
    DEFW tts_str_191
    DEFW tts_str_33
    DEFB 2
    DEFB 0x0E, 0x13
    ; rule 251: ANYTHING [R] ANYTHING
tts_rule_251:
    DEFW 0x0001
    DEFW tts_str_69
    DEFW 0x0001
    DEFB 1
    DEFB 0x0E
    ; rule 252: END
    DEFW 0x0003
    ; rule 253: ANYTHING [SH] ANYTHING
tts_rule_253:
    DEFW 0x0001
    DEFW tts_str_75
    DEFW 0x0001
    DEFB 1
    DEFB 0x25
    ; rule 254: "#" [SION] ANYTHING
tts_rule_254:
    DEFW tts_str_5
    DEFW tts_str_192
    DEFW 0x0001
    DEFB 3
    DEFB 0x26, 0x0F, 0x0B
    ; rule 255: ANYTHING [SOME] ANYTHING
tts_rule_255:
    DEFW 0x0001
    DEFW tts_str_193
    DEFW 0x0001
    DEFB 4
    DEFB 0x37, 0x0F, 0x0F, 0x10
    ; rule 256: "#" [SUR] "#"
tts_rule_256:
    DEFW tts_str_5
    DEFW tts_str_194
    DEFW tts_str_5
    DEFB 2
    DEFB 0x26, 0x33
    ; rule 257: ANYTHING [SUR] "#"
tts_rule_257:
    DEFW 0x0001
    DEFW tts_str_194
    DEFW tts_str_5
    DEFB 2
    DEFB 0x25, 0x33
    ; rule 258: "#" [SU] "#"
tts_rule_258:
    DEFW tts_str_5
    DEFW tts_str_94
    DEFW tts_str_5
    DEFB 2
    DEFB 0x26, 0x1F
    ; rule 259: "#" [SSU] "#"
tts_rule_259:
    DEFW tts_str_5
    DEFW tts_str_195
    DEFW tts_str_5
    DEFB 2
    DEFB 0x25, 0x1F
    ; rule 260: "#" [SED] "NOTHING"
tts_rule_260:
    DEFW tts_str_5
    DEFW tts_str_196
    DEFW tts_str_1
    DEFB 2
    DEFB 0x2B, 0x15
    ; rule 261: "#" [S] "#"
tts_rule_261:
    DEFW tts_str_5
    DEFW tts_str_68
    DEFW tts_str_5
    DEFB 1
    DEFB 0x2B
    ; rule 262: ANYTHING [SAID] ANYTHING
tts_rule_262:
    DEFW 0x0001
    DEFW tts_str_197
    DEFW 0x0001
    DEFB 3
    DEFB 0x37, 0x07, 0x15
    ; rule 263: "^" [SION] ANYTHING
tts_rule_263:
    DEFW tts_str_6
    DEFW tts_str_192
    DEFW 0x0001
    DEFB 3
    DEFB 0x25, 0x0F, 0x0B
    ; rule 264: ANYTHING [S] "S"
tts_rule_264:
    DEFW 0x0001
    DEFW tts_str_68
    DEFW tts_str_68
    DEFB 0
    ; rule 265: "." [S] "NOTHING"
tts_rule_265:
    DEFW tts_str_198
    DEFW tts_str_68
    DEFW tts_str_1
    DEFB 1
    DEFB 0x2B
    ; rule 266: "#:.E" [S] "NOTHING"
tts_rule_266:
    DEFW tts_str_199
    DEFW tts_str_68
    DEFW tts_str_1
    DEFB 1
    DEFB 0x2B
    ; rule 267: "#:^##" [S] "NOTHING"
tts_rule_267:
    DEFW tts_str_200
    DEFW tts_str_68
    DEFW tts_str_1
    DEFB 1
    DEFB 0x2B
    ; rule 268: "#:^#" [S] "NOTHING"
tts_rule_268:
    DEFW tts_str_201
    DEFW tts_str_68
    DEFW tts_str_1
    DEFB 1
    DEFB 0x37
    ; rule 269: "U" [S] "NOTHING"
tts_rule_269:
    DEFW tts_str_202
    DEFW tts_str_68
    DEFW tts_str_1
    DEFB 1
    DEFB 0x37
    ; rule 270: " :#" [S] "NOTHING"
tts_rule_270:
    DEFW tts_str_203
    DEFW tts_str_68
    DEFW tts_str_1
    DEFB 1
    DEFB 0x2B
    ; rule 271: "NOTHING" [SCH] ANYTHING
tts_rule_271:
    DEFW tts_str_1
    DEFW tts_str_204
    DEFW 0x0001
    DEFB 2
    DEFB 0x37, 0x2A
    ; rule 272: ANYTHING [S] "C+"
tts_rule_272:
    DEFW 0x0001
    DEFW tts_str_68
    DEFW tts_str_205
    DEFB 0
    ; rule 273: "#" [SM] ANYTHING
tts_rule_273:
    DEFW tts_str_5
    DEFW tts_str_206
    DEFW 0x0001
    DEFB 2
    DEFB 0x2B, 0x10
    ; rule 274: "#" [SN] "'"
tts_rule_274:
    DEFW tts_str_5
    DEFW tts_str_207
    DEFW tts_str_208
    DEFB 3
    DEFB 0x2B, 0x0F, 0x0B
    ; rule 275: ANYTHING [S] ANYTHING
tts_rule_275:
    DEFW 0x0001
    DEFW tts_str_68
    DEFW 0x0001
    DEFB 1
    DEFB 0x37
    ; rule 276: END
    DEFW 0x0003
    ; rule 277: "NOTHING" [THE] "NOTHING"
tts_rule_277:
    DEFW tts_str_1
    DEFW tts_str_209
    DEFW tts_str_1
    DEFB 2
    DEFB 0x12, 0x0F
    ; rule 278: ANYTHING [TO] "NOTHING"
tts_rule_278:
    DEFW 0x0001
    DEFW tts_str_210
    DEFW tts_str_1
    DEFB 2
    DEFB 0x11, 0x1F
    ; rule 279: ANYTHING [THAT] "NOTHING"
tts_rule_279:
    DEFW 0x0001
    DEFW tts_str_211
    DEFW tts_str_1
    DEFB 3
    DEFB 0x12, 0x1A, 0x11
    ; rule 280: "NOTHING" [THIS] "NOTHING"
tts_rule_280:
    DEFW tts_str_1
    DEFW tts_str_212
    DEFW tts_str_1
    DEFB 3
    DEFB 0x12, 0x0C, 0x37
    ; rule 281: "NOTHING" [THEY] ANYTHING
tts_rule_281:
    DEFW tts_str_1
    DEFW tts_str_213
    DEFW 0x0001
    DEFB 2
    DEFB 0x12, 0x14
    ; rule 282: "NOTHING" [THERE] ANYTHING
tts_rule_282:
    DEFW tts_str_1
    DEFW tts_str_214
    DEFW 0x0001
    DEFB 3
    DEFB 0x12, 0x07, 0x0E
    ; rule 283: ANYTHING [THER] ANYTHING
tts_rule_283:
    DEFW 0x0001
    DEFW tts_str_215
    DEFW 0x0001
    DEFB 2
    DEFB 0x12, 0x33
    ; rule 284: ANYTHING [THEIR] ANYTHING
tts_rule_284:
    DEFW 0x0001
    DEFW tts_str_216
    DEFW 0x0001
    DEFB 3
    DEFB 0x12, 0x07, 0x0E
    ; rule 285: "NOTHING" [THAN] "NOTHING"
tts_rule_285:
    DEFW tts_str_1
    DEFW tts_str_217
    DEFW tts_str_1
    DEFB 3
    DEFB 0x12, 0x1A, 0x0B
    ; rule 286: "NOTHING" [THEM] "NOTHING"
tts_rule_286:
    DEFW tts_str_1
    DEFW tts_str_218
    DEFW tts_str_1
    DEFB 3
    DEFB 0x12, 0x07, 0x10
    ; rule 287: ANYTHING [THESE] "NOTHING"
tts_rule_287:
    DEFW 0x0001
    DEFW tts_str_219
    DEFW tts_str_1
    DEFB 3
    DEFB 0x12, 0x13, 0x2B
    ; rule 288: "NOTHING" [THEN] ANYTHING
tts_rule_288:
    DEFW tts_str_1
    DEFW tts_str_220
    DEFW 0x0001
    DEFB 3
    DEFB 0x12, 0x07, 0x0B
    ; rule 289: ANYTHING [THROUGH] ANYTHING
tts_rule_289:
    DEFW 0x0001
    DEFW tts_str_221
    DEFW 0x0001
    DEFB 3
    DEFB 0x1D, 0x0E, 0x1F
    ; rule 290: ANYTHING [THOSE] ANYTHING
tts_rule_290:
    DEFW 0x0001
    DEFW tts_str_222
    DEFW 0x0001
    DEFB 3
    DEFB 0x12, 0x35, 0x2B
    ; rule 291: ANYTHING [THOUGH] "NOTHING"
tts_rule_291:
    DEFW 0x0001
    DEFW tts_str_223
    DEFW tts_str_1
    DEFB 2
    DEFB 0x12, 0x35
    ; rule 292: "NOTHING" [THUS] ANYTHING
tts_rule_292:
    DEFW tts_str_1
    DEFW tts_str_224
    DEFW 0x0001
    DEFB 4
    DEFB 0x12, 0x0F, 0x0F, 0x37
    ; rule 293: ANYTHING [TH] ANYTHING
tts_rule_293:
    DEFW 0x0001
    DEFW tts_str_74
    DEFW 0x0001
    DEFB 1
    DEFB 0x1D
    ; rule 294: "#:" [TED] "NOTHING"
tts_rule_294:
    DEFW tts_str_13
    DEFW tts_str_225
    DEFW tts_str_1
    DEFB 3
    DEFB 0x11, 0x0C, 0x15
    ; rule 295: "S" [TI] "#N"
tts_rule_295:
    DEFW tts_str_68
    DEFW tts_str_226
    DEFW tts_str_227
    DEFB 1
    DEFB 0x32
    ; rule 296: ANYTHING [TI] "O"
tts_rule_296:
    DEFW 0x0001
    DEFW tts_str_226
    DEFW tts_str_4
    DEFB 1
    DEFB 0x25
    ; rule 297: ANYTHING [TI] "A"
tts_rule_297:
    DEFW 0x0001
    DEFW tts_str_226
    DEFW tts_str_0
    DEFB 1
    DEFB 0x25
    ; rule 298: ANYTHING [TIEN] ANYTHING
tts_rule_298:
    DEFW 0x0001
    DEFW tts_str_228
    DEFW 0x0001
    DEFB 3
    DEFB 0x25, 0x0F, 0x0B
    ; rule 299: ANYTHING [TUR] "#"
tts_rule_299:
    DEFW 0x0001
    DEFW tts_str_229
    DEFW tts_str_5
    DEFB 2
    DEFB 0x32, 0x33
    ; rule 300: ANYTHING [TU] "A"
tts_rule_300:
    DEFW 0x0001
    DEFW tts_str_230
    DEFW tts_str_0
    DEFB 2
    DEFB 0x32, 0x1F
    ; rule 301: "NOTHING" [TWO] ANYTHING
tts_rule_301:
    DEFW tts_str_1
    DEFW tts_str_231
    DEFW 0x0001
    DEFB 2
    DEFB 0x11, 0x1F
    ; rule 302: ANYTHING [T] ANYTHING
tts_rule_302:
    DEFW 0x0001
    DEFW tts_str_66
    DEFW 0x0001
    DEFB 1
    DEFB 0x11
    ; rule 303: END
    DEFW 0x0003
    ; rule 304: "NOTHING" [UN] "I"
tts_rule_304:
    DEFW tts_str_1
    DEFW tts_str_232
    DEFW tts_str_117
    DEFB 3
    DEFB 0x31, 0x1F, 0x0B
    ; rule 305: "NOTHING" [UN] ANYTHING
tts_rule_305:
    DEFW tts_str_1
    DEFW tts_str_232
    DEFW 0x0001
    DEFB 3
    DEFB 0x0F, 0x0F, 0x0B
    ; rule 306: "NOTHING" [UPON] ANYTHING
tts_rule_306:
    DEFW tts_str_1
    DEFW tts_str_233
    DEFW 0x0001
    DEFB 4
    DEFB 0x0F, 0x09, 0x17, 0x0B
    ; rule 307: "T" [UR] "#"
tts_rule_307:
    DEFW tts_str_66
    DEFW tts_str_234
    DEFW tts_str_5
    DEFB 2
    DEFB 0x1E, 0x0E
    ; rule 308: "S" [UR] "#"
tts_rule_308:
    DEFW tts_str_68
    DEFW tts_str_234
    DEFW tts_str_5
    DEFB 2
    DEFB 0x1E, 0x0E
    ; rule 309: "R" [UR] "#"
tts_rule_309:
    DEFW tts_str_69
    DEFW tts_str_234
    DEFW tts_str_5
    DEFB 2
    DEFB 0x1E, 0x0E
    ; rule 310: "D" [UR] "#"
tts_rule_310:
    DEFW tts_str_50
    DEFW tts_str_234
    DEFW tts_str_5
    DEFB 2
    DEFB 0x1E, 0x0E
    ; rule 311: "L" [UR] "#"
tts_rule_311:
    DEFW tts_str_70
    DEFW tts_str_234
    DEFW tts_str_5
    DEFB 2
    DEFB 0x1E, 0x0E
    ; rule 312: "Z" [UR] "#"
tts_rule_312:
    DEFW tts_str_71
    DEFW tts_str_234
    DEFW tts_str_5
    DEFB 2
    DEFB 0x1E, 0x0E
    ; rule 313: "N" [UR] "#"
tts_rule_313:
    DEFW tts_str_72
    DEFW tts_str_234
    DEFW tts_str_5
    DEFB 2
    DEFB 0x1E, 0x0E
    ; rule 314: "J" [UR] "#"
tts_rule_314:
    DEFW tts_str_73
    DEFW tts_str_234
    DEFW tts_str_5
    DEFB 2
    DEFB 0x1E, 0x0E
    ; rule 315: "TH" [UR] "#"
tts_rule_315:
    DEFW tts_str_74
    DEFW tts_str_234
    DEFW tts_str_5
    DEFB 2
    DEFB 0x1E, 0x0E
    ; rule 316: "CH" [UR] "#"
tts_rule_316:
    DEFW tts_str_39
    DEFW tts_str_234
    DEFW tts_str_5
    DEFB 2
    DEFB 0x1E, 0x0E
    ; rule 317: "SH" [UR] "#"
tts_rule_317:
    DEFW tts_str_75
    DEFW tts_str_234
    DEFW tts_str_5
    DEFB 2
    DEFB 0x1E, 0x0E
    ; rule 318: ANYTHING [UR] "#"
tts_rule_318:
    DEFW 0x0001
    DEFW tts_str_234
    DEFW tts_str_5
    DEFB 3
    DEFB 0x31, 0x1E, 0x0E
    ; rule 319: ANYTHING [UR] ANYTHING
tts_rule_319:
    DEFW 0x0001
    DEFW tts_str_234
    DEFW 0x0001
    DEFB 1
    DEFB 0x33
    ; rule 320: ANYTHING [U] "^ "
tts_rule_320:
    DEFW 0x0001
    DEFW tts_str_202
    DEFW tts_str_235
    DEFB 2
    DEFB 0x0F, 0x0F
    ; rule 321: ANYTHING [U] "^^"
tts_rule_321:
    DEFW 0x0001
    DEFW tts_str_202
    DEFW tts_str_236
    DEFB 2
    DEFB 0x0F, 0x0F
    ; rule 322: ANYTHING [UY] ANYTHING
tts_rule_322:
    DEFW 0x0001
    DEFW tts_str_237
    DEFW 0x0001
    DEFB 1
    DEFB 0x06
    ; rule 323: " G" [U] "#"
tts_rule_323:
    DEFW tts_str_238
    DEFW tts_str_202
    DEFW tts_str_5
    DEFB 0
    ; rule 324: "G" [U] "%"
tts_rule_324:
    DEFW tts_str_103
    DEFW tts_str_202
    DEFW tts_str_47
    DEFB 0
    ; rule 325: "G" [U] "#"
tts_rule_325:
    DEFW tts_str_103
    DEFW tts_str_202
    DEFW tts_str_5
    DEFB 1
    DEFB 0x2E
    ; rule 326: "#N" [U] ANYTHING
tts_rule_326:
    DEFW tts_str_227
    DEFW tts_str_202
    DEFW 0x0001
    DEFB 2
    DEFB 0x31, 0x1F
    ; rule 327: "T" [U] ANYTHING
tts_rule_327:
    DEFW tts_str_66
    DEFW tts_str_202
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 328: "S" [U] ANYTHING
tts_rule_328:
    DEFW tts_str_68
    DEFW tts_str_202
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 329: "R" [U] ANYTHING
tts_rule_329:
    DEFW tts_str_69
    DEFW tts_str_202
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 330: "D" [U] ANYTHING
tts_rule_330:
    DEFW tts_str_50
    DEFW tts_str_202
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 331: "L" [U] ANYTHING
tts_rule_331:
    DEFW tts_str_70
    DEFW tts_str_202
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 332: "Z" [U] ANYTHING
tts_rule_332:
    DEFW tts_str_71
    DEFW tts_str_202
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 333: "N" [U] ANYTHING
tts_rule_333:
    DEFW tts_str_72
    DEFW tts_str_202
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 334: "J" [U] ANYTHING
tts_rule_334:
    DEFW tts_str_73
    DEFW tts_str_202
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 335: "TH" [U] ANYTHING
tts_rule_335:
    DEFW tts_str_74
    DEFW tts_str_202
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 336: "CH" [U] ANYTHING
tts_rule_336:
    DEFW tts_str_39
    DEFW tts_str_202
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 337: "SH" [U] ANYTHING
tts_rule_337:
    DEFW tts_str_75
    DEFW tts_str_202
    DEFW 0x0001
    DEFB 1
    DEFB 0x1F
    ; rule 338: ANYTHING [U] ANYTHING
tts_rule_338:
    DEFW 0x0001
    DEFW tts_str_202
    DEFW 0x0001
    DEFB 2
    DEFB 0x31, 0x1F
    ; rule 339: END
    DEFW 0x0003
    ; rule 340: ANYTHING [VIEW] ANYTHING
tts_rule_340:
    DEFW 0x0001
    DEFW tts_str_239
    DEFW 0x0001
    DEFB 3
    DEFB 0x23, 0x31, 0x1F
    ; rule 341: ANYTHING [V] ANYTHING
tts_rule_341:
    DEFW 0x0001
    DEFW tts_str_240
    DEFW 0x0001
    DEFB 1
    DEFB 0x23
    ; rule 342: END
    DEFW 0x0003
    ; rule 343: "NOTHING" [WERE] ANYTHING
tts_rule_343:
    DEFW tts_str_1
    DEFW tts_str_241
    DEFW 0x0001
    DEFB 2
    DEFB 0x2E, 0x33
    ; rule 344: ANYTHING [WA] "S"
tts_rule_344:
    DEFW 0x0001
    DEFW tts_str_8
    DEFW tts_str_68
    DEFB 2
    DEFB 0x2E, 0x18
    ; rule 345: ANYTHING [WA] "T"
tts_rule_345:
    DEFW 0x0001
    DEFW tts_str_8
    DEFW tts_str_66
    DEFB 2
    DEFB 0x2E, 0x18
    ; rule 346: ANYTHING [WHERE] ANYTHING
tts_rule_346:
    DEFW 0x0001
    DEFW tts_str_242
    DEFW 0x0001
    DEFB 3
    DEFB 0x30, 0x07, 0x0E
    ; rule 347: ANYTHING [WHAT] ANYTHING
tts_rule_347:
    DEFW 0x0001
    DEFW tts_str_243
    DEFW 0x0001
    DEFB 3
    DEFB 0x30, 0x18, 0x11
    ; rule 348: ANYTHING [WHOL] ANYTHING
tts_rule_348:
    DEFW 0x0001
    DEFW tts_str_244
    DEFW 0x0001
    DEFB 3
    DEFB 0x1B, 0x35, 0x2D
    ; rule 349: ANYTHING [WHO] ANYTHING
tts_rule_349:
    DEFW 0x0001
    DEFW tts_str_245
    DEFW 0x0001
    DEFB 2
    DEFB 0x1B, 0x1F
    ; rule 350: ANYTHING [WH] ANYTHING
tts_rule_350:
    DEFW 0x0001
    DEFW tts_str_246
    DEFW 0x0001
    DEFB 1
    DEFB 0x30
    ; rule 351: ANYTHING [WAR] ANYTHING
tts_rule_351:
    DEFW 0x0001
    DEFW tts_str_247
    DEFW 0x0001
    DEFB 3
    DEFB 0x2E, 0x17, 0x0E
    ; rule 352: ANYTHING [WOR] "^"
tts_rule_352:
    DEFW 0x0001
    DEFW tts_str_248
    DEFW tts_str_6
    DEFB 2
    DEFB 0x2E, 0x33
    ; rule 353: ANYTHING [WR] ANYTHING
tts_rule_353:
    DEFW 0x0001
    DEFW tts_str_249
    DEFW 0x0001
    DEFB 1
    DEFB 0x0E
    ; rule 354: ANYTHING [W] ANYTHING
tts_rule_354:
    DEFW 0x0001
    DEFW tts_str_65
    DEFW 0x0001
    DEFB 1
    DEFB 0x2E
    ; rule 355: END
    DEFW 0x0003
    ; rule 356: ANYTHING [X] ANYTHING
tts_rule_356:
    DEFW 0x0001
    DEFW tts_str_250
    DEFW 0x0001
    DEFB 2
    DEFB 0x2A, 0x37
    ; rule 357: END
    DEFW 0x0003
    ; rule 358: ANYTHING [YOUNG] ANYTHING
tts_rule_358:
    DEFW 0x0001
    DEFW tts_str_251
    DEFW 0x0001
    DEFB 4
    DEFB 0x31, 0x0F, 0x0F, 0x2C
    ; rule 359: "NOTHING" [YOU] ANYTHING
tts_rule_359:
    DEFW tts_str_1
    DEFW tts_str_252
    DEFW 0x0001
    DEFB 2
    DEFB 0x31, 0x1F
    ; rule 360: "NOTHING" [YES] ANYTHING
tts_rule_360:
    DEFW tts_str_1
    DEFW tts_str_253
    DEFW 0x0001
    DEFB 3
    DEFB 0x31, 0x07, 0x37
    ; rule 361: "NOTHING" [Y] ANYTHING
tts_rule_361:
    DEFW tts_str_1
    DEFW tts_str_254
    DEFW 0x0001
    DEFB 1
    DEFB 0x31
    ; rule 362: "#:^" [Y] "NOTHING"
tts_rule_362:
    DEFW tts_str_130
    DEFW tts_str_254
    DEFW tts_str_1
    DEFB 1
    DEFB 0x13
    ; rule 363: "#:^" [Y] "I"
tts_rule_363:
    DEFW tts_str_130
    DEFW tts_str_254
    DEFW tts_str_117
    DEFB 1
    DEFB 0x13
    ; rule 364: " :" [Y] "NOTHING"
tts_rule_364:
    DEFW tts_str_10
    DEFW tts_str_254
    DEFW tts_str_1
    DEFB 1
    DEFB 0x06
    ; rule 365: " :" [Y] "#"
tts_rule_365:
    DEFW tts_str_10
    DEFW tts_str_254
    DEFW tts_str_5
    DEFB 1
    DEFB 0x06
    ; rule 366: " :" [Y] "^+:#"
tts_rule_366:
    DEFW tts_str_10
    DEFW tts_str_254
    DEFW tts_str_19
    DEFB 1
    DEFB 0x0C
    ; rule 367: " :" [Y] "^#"
tts_rule_367:
    DEFW tts_str_10
    DEFW tts_str_254
    DEFW tts_str_33
    DEFB 1
    DEFB 0x06
    ; rule 368: ANYTHING [Y] ANYTHING
tts_rule_368:
    DEFW 0x0001
    DEFW tts_str_254
    DEFW 0x0001
    DEFB 1
    DEFB 0x0C
    ; rule 369: END
    DEFW 0x0003
    ; rule 370: ANYTHING [Z] ANYTHING
tts_rule_370:
    DEFW 0x0001
    DEFW tts_str_71
    DEFW 0x0001
    DEFB 1
    DEFB 0x2B
    ; rule 371: END
    DEFW 0x0003
    ; rule 372: ANYTHING [0] ANYTHING
tts_rule_372:
    DEFW 0x0001
    DEFW tts_str_255
    DEFW 0x0001
    DEFB 4
    DEFB 0x2B, 0x0C, 0x0E, 0x35
    ; rule 373: ANYTHING [1] ANYTHING
tts_rule_373:
    DEFW 0x0001
    DEFW tts_str_256
    DEFW 0x0001
    DEFB 4
    DEFB 0x2E, 0x0F, 0x0F, 0x0B
    ; rule 374: ANYTHING [2] ANYTHING
tts_rule_374:
    DEFW 0x0001
    DEFW tts_str_257
    DEFW 0x0001
    DEFB 2
    DEFB 0x11, 0x1F
    ; rule 375: ANYTHING [3] ANYTHING
tts_rule_375:
    DEFW 0x0001
    DEFW tts_str_258
    DEFW 0x0001
    DEFB 3
    DEFB 0x1D, 0x0E, 0x13
    ; rule 376: ANYTHING [4] ANYTHING
tts_rule_376:
    DEFW 0x0001
    DEFW tts_str_259
    DEFW 0x0001
    DEFB 3
    DEFB 0x28, 0x35, 0x0E
    ; rule 377: ANYTHING [5] ANYTHING
tts_rule_377:
    DEFW 0x0001
    DEFW tts_str_260
    DEFW 0x0001
    DEFB 3
    DEFB 0x28, 0x06, 0x23
    ; rule 378: ANYTHING [6] ANYTHING
tts_rule_378:
    DEFW 0x0001
    DEFW tts_str_261
    DEFW 0x0001
    DEFB 4
    DEFB 0x37, 0x0C, 0x2A, 0x37
    ; rule 379: ANYTHING [7] ANYTHING
tts_rule_379:
    DEFW 0x0001
    DEFW tts_str_262
    DEFW 0x0001
    DEFB 5
    DEFB 0x37, 0x07, 0x23, 0x0F, 0x0B
    ; rule 380: ANYTHING [8] ANYTHING
tts_rule_380:
    DEFW 0x0001
    DEFW tts_str_263
    DEFW 0x0001
    DEFB 2
    DEFB 0x14, 0x11
    ; rule 381: ANYTHING [9] ANYTHING
tts_rule_381:
    DEFW 0x0001
    DEFW tts_str_264
    DEFW 0x0001
    DEFB 3
    DEFB 0x0B, 0x06, 0x0B
    ; rule 382: END
    DEFW 0x0003
    ; rule 383: ANYTHING [ ] ANYTHING
tts_rule_383:
    DEFW 0x0001
    DEFW tts_str_1
    DEFW 0x0001
    DEFB 1
    DEFB 0x03
    ; rule 384: ANYTHING [--] ANYTHING
tts_rule_384:
    DEFW 0x0001
    DEFW tts_str_265
    DEFW 0x0001
    DEFB 1
    DEFB 0x03
    ; rule 385: ANYTHING [-] ANYTHING
tts_rule_385:
    DEFW 0x0001
    DEFW tts_str_266
    DEFW 0x0001
    DEFB 0
    ; rule 386: "." ['S] ANYTHING
tts_rule_386:
    DEFW tts_str_198
    DEFW tts_str_267
    DEFW 0x0001
    DEFB 1
    DEFB 0x2B
    ; rule 387: "#:.E" ['S] ANYTHING
tts_rule_387:
    DEFW tts_str_199
    DEFW tts_str_267
    DEFW 0x0001
    DEFB 1
    DEFB 0x2B
    ; rule 388: "#" ['S] ANYTHING
tts_rule_388:
    DEFW tts_str_5
    DEFW tts_str_267
    DEFW 0x0001
    DEFB 1
    DEFB 0x2B
    ; rule 389: ANYTHING ['] ANYTHING
tts_rule_389:
    DEFW 0x0001
    DEFW tts_str_208
    DEFW 0x0001
    DEFB 0
    ; rule 390: ANYTHING [,] ANYTHING
tts_rule_390:
    DEFW 0x0001
    DEFW tts_str_268
    DEFW 0x0001
    DEFB 1
    DEFB 0x03
    ; rule 391: ANYTHING [.] ANYTHING
tts_rule_391:
    DEFW 0x0001
    DEFW tts_str_198
    DEFW 0x0001
    DEFB 1
    DEFB 0x03
    ; rule 392: ANYTHING [?] ANYTHING
tts_rule_392:
    DEFW 0x0001
    DEFW tts_str_269
    DEFW 0x0001
    DEFB 1
    DEFB 0x03
    ; rule 393: ANYTHING [!] ANYTHING
tts_rule_393:
    DEFW 0x0001
    DEFW tts_str_270
    DEFW 0x0001
    DEFB 1
    DEFB 0x03
    ; rule 394: ANYTHING [@] ANYTHING
tts_rule_394:
    DEFW 0x0001
    DEFW tts_str_271
    DEFW 0x0001
    DEFB 2
    DEFB 0x1A, 0x11
    ; rule 395: END
    DEFW 0x0003
    ; rule 396: END
    DEFW 0x0003

; ------------------------------------------------------------
; Rule map: for each ASCII char (0-127), pointer to first rule
; 0x0000 = no rules for this character
; ------------------------------------------------------------
tts_rulemap:
    DEFW 0x0000                         ;   0
    DEFW 0x0000                         ;   1
    DEFW 0x0000                         ;   2
    DEFW 0x0000                         ;   3
    DEFW 0x0000                         ;   4
    DEFW 0x0000                         ;   5
    DEFW 0x0000                         ;   6
    DEFW 0x0000                         ;   7
    DEFW 0x0000                         ;   8
    DEFW 0x0000                         ;   9
    DEFW 0x0000                         ;  10
    DEFW 0x0000                         ;  11
    DEFW 0x0000                         ;  12
    DEFW 0x0000                         ;  13
    DEFW 0x0000                         ;  14
    DEFW 0x0000                         ;  15
    DEFW 0x0000                         ;  16
    DEFW 0x0000                         ;  17
    DEFW 0x0000                         ;  18
    DEFW 0x0000                         ;  19
    DEFW 0x0000                         ;  20
    DEFW 0x0000                         ;  21
    DEFW 0x0000                         ;  22
    DEFW 0x0000                         ;  23
    DEFW 0x0000                         ;  24
    DEFW 0x0000                         ;  25
    DEFW 0x0000                         ;  26
    DEFW 0x0000                         ;  27
    DEFW 0x0000                         ;  28
    DEFW 0x0000                         ;  29
    DEFW 0x0000                         ;  30
    DEFW 0x0000                         ;  31
    DEFW tts_rule_383                   ;  32  
    DEFW tts_rule_383                   ;  33 !
    DEFW 0x0000                         ;  34 "
    DEFW 0x0000                         ;  35 #
    DEFW 0x0000                         ;  36 $
    DEFW 0x0000                         ;  37 %
    DEFW 0x0000                         ;  38 &
    DEFW tts_rule_383                   ;  39 '
    DEFW 0x0000                         ;  40 (
    DEFW 0x0000                         ;  41 )
    DEFW 0x0000                         ;  42 *
    DEFW 0x0000                         ;  43 +
    DEFW tts_rule_383                   ;  44 ,
    DEFW tts_rule_383                   ;  45 -
    DEFW tts_rule_383                   ;  46 .
    DEFW 0x0000                         ;  47 /
    DEFW tts_rule_372                   ;  48 0
    DEFW tts_rule_372                   ;  49 1
    DEFW tts_rule_372                   ;  50 2
    DEFW tts_rule_372                   ;  51 3
    DEFW tts_rule_372                   ;  52 4
    DEFW tts_rule_372                   ;  53 5
    DEFW tts_rule_372                   ;  54 6
    DEFW tts_rule_372                   ;  55 7
    DEFW tts_rule_372                   ;  56 8
    DEFW tts_rule_372                   ;  57 9
    DEFW tts_rule_383                   ;  58 :
    DEFW 0x0000                         ;  59 ;
    DEFW 0x0000                         ;  60 <
    DEFW 0x0000                         ;  61 =
    DEFW 0x0000                         ;  62 >
    DEFW tts_rule_383                   ;  63 ?
    DEFW tts_rule_383                   ;  64 @
    DEFW tts_rule_0                     ;  65 A
    DEFW tts_rule_34                    ;  66 B
    DEFW tts_rule_41                    ;  67 C
    DEFW tts_rule_53                    ;  68 D
    DEFW tts_rule_64                    ;  69 E
    DEFW tts_rule_117                   ;  70 F
    DEFW tts_rule_120                   ;  71 G
    DEFW tts_rule_131                   ;  72 H
    DEFW tts_rule_138                   ;  73 I
    DEFW tts_rule_167                   ;  74 J
    DEFW tts_rule_169                   ;  75 K
    DEFW tts_rule_172                   ;  76 L
    DEFW tts_rule_178                   ;  77 M
    DEFW tts_rule_181                   ;  78 N
    DEFW tts_rule_190                   ;  79 O
    DEFW tts_rule_240                   ;  80 P
    DEFW tts_rule_246                   ;  81 Q
    DEFW tts_rule_250                   ;  82 R
    DEFW tts_rule_253                   ;  83 S
    DEFW tts_rule_277                   ;  84 T
    DEFW tts_rule_304                   ;  85 U
    DEFW tts_rule_340                   ;  86 V
    DEFW tts_rule_343                   ;  87 W
    DEFW tts_rule_356                   ;  88 X
    DEFW tts_rule_358                   ;  89 Y
    DEFW tts_rule_370                   ;  90 Z
    DEFW 0x0000                         ;  91 [
    DEFW 0x0000                         ;  92 \
    DEFW 0x0000                         ;  93 ]
    DEFW 0x0000                         ;  94 ^
    DEFW 0x0000                         ;  95 _
    DEFW 0x0000                         ;  96 `
    DEFW tts_rule_0                     ;  97 a
    DEFW tts_rule_34                    ;  98 b
    DEFW tts_rule_41                    ;  99 c
    DEFW tts_rule_53                    ; 100 d
    DEFW tts_rule_64                    ; 101 e
    DEFW tts_rule_117                   ; 102 f
    DEFW tts_rule_120                   ; 103 g
    DEFW tts_rule_131                   ; 104 h
    DEFW tts_rule_138                   ; 105 i
    DEFW tts_rule_167                   ; 106 j
    DEFW tts_rule_169                   ; 107 k
    DEFW tts_rule_172                   ; 108 l
    DEFW tts_rule_178                   ; 109 m
    DEFW tts_rule_181                   ; 110 n
    DEFW tts_rule_190                   ; 111 o
    DEFW tts_rule_240                   ; 112 p
    DEFW tts_rule_246                   ; 113 q
    DEFW tts_rule_250                   ; 114 r
    DEFW tts_rule_253                   ; 115 s
    DEFW tts_rule_277                   ; 116 t
    DEFW tts_rule_304                   ; 117 u
    DEFW tts_rule_340                   ; 118 v
    DEFW tts_rule_343                   ; 119 w
    DEFW tts_rule_356                   ; 120 x
    DEFW tts_rule_358                   ; 121 y
    DEFW tts_rule_370                   ; 122 z
    DEFW 0x0000                         ; 123 {
    DEFW 0x0000                         ; 124 |
    DEFW 0x0000                         ; 125 }
    DEFW 0x0000                         ; 126 ~
    DEFW 0x0000                         ; 127

